// Generated by purs version 0.12.1
"use strict";
var $foreign = require("./foreign.js");
var Effect = require("../Effect/index.js");
module.exports = {
    unsafePerformEffect: $foreign.unsafePerformEffect
};
