// Generated by purs version 0.12.1
"use strict";
var Effect = require("../Effect/index.js");
var Effect_Console = require("../Effect.Console/index.js");
var Prelude = require("../Prelude/index.js");
var main = Effect_Console.log("Hello sailor!");
module.exports = {
    main: main
};
